# user id 설정
user_id: user
# 기본 경로 설정
base_path: "/mnt/AI_NAS/datalake"

# Processing 서버 URL
server_url: "http://192.168.20.62:8091"

# 로그 레벨 (DEBUG, INFO, WARNING, ERROR)
log_level: "INFO"

# 병렬 처리 프로세스 수
num_proc: 16